# Generated by Django 5.1.3 on 2025-05-05 15:11

import django.db.models.deletion
import finance.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('iban', models.CharField(max_length=255, unique=True)),
                ('bic', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_iban', models.CharField(max_length=255)),
                ('applicant_bic', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=255)),
                ('posting_text', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('additional_purpose', models.TextField()),
                ('entry_date', models.DateField()),
                ('date', models.DateField()),
                ('data', models.JSONField(encoder=finance.json.MT940Encoder)),
                ('checksum', models.CharField(max_length=255)),
                ('order_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.orderaccount')),
            ],
        ),
    ]
