# Generated by Django 5.1.3 on 2025-10-18 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('searchkit', '0003_search_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchToAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.orderaccount')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchkit.search')),
            ],
        ),
    ]
